services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\Persons\:
    resource: '../Classes/*'
    exclude: ['../Classes/Event/*']


  CPSIT\Persons\Listener\PersonControllerListener:
    public: false
    tags:
      - name: event.listener
        identifier: 'persons-event-listener-filter-before-assign'
        event: CPSIT\Persons\Event\PersonsHandleFilterBeforeAssignEvent
        method: 'handleFilterBeforeAssign'
      - name: event.listener
        identifier: 'persons-event-listener-list-before-assign'
        event: CPSIT\Persons\Event\PersonsHandleListBeforeAssignEvent
        method: 'handleListBeforeAssign'